Repository Jakobnr1/MoneyServiceGruppArbete, pull requests merged in 2021-04, with the labels that each got.

#26 Albin develop
  Documents/MoneyServiceProject.uxf
  src/MoneyService/Order.java
Labels: enhancement

#27 Jakob
  .gitignore
  src/MoneyService/ExchangeRate.java
  src/Test.ser
  src/Test.txt
Labels: documentation

#29 Changed UML
  Documents/MoneyServiceProject.uxf
Labels: documentation

#31 Jakob
  src/MoneyService/ExchangeRate.java
  src/MoneyService/MoneyServiceIO.java
Labels: invalid

#45 Worked on ExchangeSite with Peter
  Documents/Readme.md
  src/MoneyService/ExchangeRate.java
  src/MoneyService/ExchangeSite.java
  src/MoneyService/MoneyBox.java
  src/MoneyService/MoneyService.java
Labels: enhancement

#44 Changed Currency and MoneyBox
  Documents/MoneyServiceProject.uxf
  Test.ser
  Test.txt
  src/MoneyService/Currency.java
  src/MoneyService/MoneyBox.java
  src/MoneyServiceAPP/TestApp.java
  test/MoneyService/TestCurrency.java
  test/MoneyService/TestMoneyBox.java
Labels: enhancement

#49 Added local refdate to Order
  src/MoneyService/Order.java
Labels: enhancement

#50 Started a bit more on Exchangesite and testExchangesite
  src/MoneyService/ExchangeSite.java
  test/MoneyService/TestExchangeSite.java
Labels: enhancement

#63 Albin develop
  Documents/MoneyServiceProject.uxf
  src/MoneyService/Order.java
  src/MoneyService/Transaction.java
Labels: enhancement

#66 Added comments to code
  src/MoneyService/ExchangeSite.java
Labels: documentation

#67 finalized ExchangeSite, need some methods implemented in currency
  src/MoneyService/Config.java
  src/MoneyService/ExchangeSite.java
  src/MoneyService/MoneyServiceIO.java
  src/MoneyService/Order.java
Labels: help wanted

#74 Fixed and maybe finished ExchangeSite
  Report_NORTH_2021-04-19.ser
  src/MoneyService/Currency.java
  src/MoneyService/ExchangeSite.java
Labels: enhancement, good first issue

#77 Changed a bit in ExchangeSite and fixed all tests
  src/MoneyService/ExchangeSite.java
  test/MoneyService/TestExchangeSite.java
Labels: enhancement

#81 Fixed test for classes and fixed 5 ser files for customer
  CurrencyConfig_2021-04-19.txt
  CurrencyConfig_2021-04-20.txt
  CurrencyConfig_2021-04-21.txt
  CurrencyConfig_2021-04-22.txt
  CurrencyConfig_2021-04-23.txt
  Documents/ProjectConfig_2021-04-01.txt
  MoneyServiceLog.txt
  ProjectConfig_2021-04-19.txt
  ProjectConfig_2021-04-20.txt
  ProjectConfig_2021-04-21.txt
  ProjectConfig_2021-04-22.txt
  ProjectConfig_2021-04-23.txt
  Report_NORTH_2021-04-16.ser
  Report_NORTH_2021-04-19.ser
  Report_NORTH_2021-04-20
  Report_North_2021-04-20.ser
  Report_North_2021-04-21.ser
  Report_North_2021-04-21.txt
  Report_North_2021-04-212.txt
  Report_North_2021-04-22.ser
  Report_North_2021-04-23.ser
  curren.txt
  src/MoneyService/Config.java
  src/MoneyService/Currency.java
  src/MoneyService/MoneyBox.java
  src/MoneyService/MoneyServiceIO.java
  src/MoneyServiceAPP/MoneyServiceAPP.java
  test/MoneyService/AllTests.java
  test/MoneyService/TestCurrency.java
  test/MoneyService/TestExchangeSite.java
  test/MoneyService/TestMoneyBox.java
  test/MoneyService/testConfig.java
  test/MoneyService/testExchangeRate.java
Labels: enhancement

#88 Added denominationControl() method in MoneyBox
  src/MoneyServiceAPP/MoneyServiceAPP.java
  src/affix/java/project/moneyservice/Config.java
  src/affix/java/project/moneyservice/MoneyBox.java
Labels: enhancement

#93 Changed MoneyServiceIO
  CurrencyConfig_2021-04-27.txt
  ProjectConfig_2021-04-27.txt
  Report_North_2021-04-27.ser
  TestFile.ser
  TestList3.txt
  src/affix/java/project/moneyservice/ExchangeSite.java
  src/affix/java/project/moneyservice/MoneyServiceIO.java
  test/MoneyService/testExchangeRate.java
  test/MoneyService/testMoneyServiceIO.java
  test2.txt
  testTesxt4.txt
Labels: enhancement

#100 Git bråkar med mig
  src/MoneyServiceAPP/MoneyServiceAPP.java
  src/affix/java/project/moneyservice/ExchangeSite.java
  src/affix/java/project/moneyservice/MoneyServiceIO.java
  src/affix/java/project/moneyservice/Transaction.java
Labels: bug
