Repository Jakobnr1/MoneyServiceGruppArbete, pull requests merged in 2021-05, with the labels that each got.

#106 Fixed a setter... again
  src/affix/java/project/moneyservice/MoneyServiceIO.java
Labels: bug

#116 Added a Queue system
  src/affix/java/project/moneyservice/ExchangeSite.java
Labels: enhancement

#125 Added Config FilePath configuration
  configFileNorthTest.txt
  src/affix/java/project/moneyservice/Config.java
  src/affix/java/project/moneyservice/MoneyServiceIO.java
Labels: enhancement

#127 Changed some static to non static
  src/MoneyServiceAPP/MoneyServiceAPP.java
  src/affix/java/project/moneyservice/ExchangeSite.java
  src/affix/java/project/moneyservice/Report.java
  test/MoneyService/testMoneyServiceIO.java
  test/MoneyService/testReport.java
Labels: bug

#132 Fixed stuff that Kjell talked about, and something else i forgot
  src/MoneyServiceAPP/MoneyServiceAPP.java
  src/affix/java/project/moneyservice/ExchangeSite.java
Labels: documentation

#133 Added Documentation to MoneyBox and Order
  src/affix/java/project/moneyservice/MoneyBox.java
  src/affix/java/project/moneyservice/MonyeServiceLoggFilter.java
  src/affix/java/project/moneyservice/Order.java
  src/affix/java/project/moneyservice/Transaction.java
Labels: documentation

#137 Added a userguide for MoneyService
  Documents/Userguide-for-Money-Service.docx
Labels: documentation

#154 Albin
  src/MoneyServiceAPP/MoneyServiceAPP.java
  src/MoneyServiceAPP/MoneyServiceGUI.java
  src/MoneyServiceAPP/MoneyServiceView.java
Labels: bug
